name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint
        env:
          ESLINT_CONFIG: .config/.eslintrc.json

      - name: Run formatter
        run: npm run format
        env:
          PRETTIER_CONFIG: .config/.prettierrc

      - name: Build project
        run: npm run build
        env:
          TS_NODE_PROJECT: .config/tsconfig.json

      - name: Run tests
        run: npm test
        env:
          JEST_CONFIG: .config/jest.config.json
